/**
 * Known Merchants Database Seed Data
 * 
 * Comprehensive list of 200+ US and UK subscription services
 * Includes keyword variations, payment processor patterns, and typical pricing
 */

export interface KnownMerchantSeed {
  name: string;
  displayName: string;
  category: string;
  logoUrl?: string;
  website?: string;
  keywords: string[];
  countries: string[];
  currency: string[];
  typicalAmounts: Record<string, number>;
  billingCycles: string[];
}

export const knownMerchants: KnownMerchantSeed[] = [
  // ============================================
  // STREAMING SERVICES (30)
  // ============================================
  {
    name: 'Netflix',
    displayName: 'Netflix',
    category: 'Streaming',
    website: 'https://netflix.com',
    keywords: ['netflix', 'nflx', 'netflix.com', 'netflix inc', 'netflix*', 'nflx*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 15.49, GBP: 10.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Disney Plus',
    displayName: 'Disney+',
    category: 'Streaming',
    website: 'https://disneyplus.com',
    keywords: ['disney', 'disney+', 'disney plus', 'disneyplus', 'disney streaming', 'disney*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 10.99, GBP: 7.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Hulu',
    displayName: 'Hulu',
    category: 'Streaming',
    website: 'https://hulu.com',
    keywords: ['hulu', 'hulu.com', 'hulu*', 'hulu llc'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 7.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Max',
    displayName: 'Max (HBO Max)',
    category: 'Streaming',
    website: 'https://max.com',
    keywords: ['max', 'hbo max', 'hbomax', 'hbo', 'warner bros', 'max.com', 'hbo*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 15.99, GBP: 9.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Prime Video',
    displayName: 'Amazon Prime Video',
    category: 'Streaming',
    website: 'https://primevideo.com',
    keywords: ['prime video', 'amazon prime', 'primevideo', 'amzn.com/bill', 'amazon prime video', 'amazon*prime'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 8.99, GBP: 5.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Apple TV Plus',
    displayName: 'Apple TV+',
    category: 'Streaming',
    website: 'https://tv.apple.com',
    keywords: ['apple tv', 'appletv', 'apple tv+', 'apple.com/bill', 'apple*', 'itunes'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 6.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'YouTube Premium',
    displayName: 'YouTube Premium',
    category: 'Streaming',
    website: 'https://youtube.com/premium',
    keywords: ['youtube', 'youtube premium', 'youtube red', 'google*youtube', 'google*youtube premium', 'yt premium'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 13.99, GBP: 11.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Spotify',
    displayName: 'Spotify',
    category: 'Streaming',
    website: 'https://spotify.com',
    keywords: ['spotify', 'spotify.com', 'spotify*', 'spotify premium', 'spotify usa'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 10.99, GBP: 10.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Pandora',
    displayName: 'Pandora',
    category: 'Streaming',
    website: 'https://pandora.com',
    keywords: ['pandora', 'pandora.com', 'pandora*', 'pandora plus', 'pandora premium'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 9.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Peacock',
    displayName: 'Peacock',
    category: 'Streaming',
    website: 'https://peacocktv.com',
    keywords: ['peacock', 'peacock tv', 'peacocktv', 'nbc peacock', 'peacock*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 5.99, GBP: 4.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Paramount Plus',
    displayName: 'Paramount+',
    category: 'Streaming',
    website: 'https://paramountplus.com',
    keywords: ['paramount', 'paramount+', 'paramount plus', 'paramountplus', 'cbs all access', 'paramount*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 5.99, GBP: 6.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Discovery Plus',
    displayName: 'Discovery+',
    category: 'Streaming',
    website: 'https://discoveryplus.com',
    keywords: ['discovery', 'discovery+', 'discovery plus', 'discoveryplus', 'discovery*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 4.99, GBP: 4.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Crunchyroll',
    displayName: 'Crunchyroll',
    category: 'Streaming',
    website: 'https://crunchyroll.com',
    keywords: ['crunchyroll', 'crunchyroll.com', 'crunchyroll*', 'cr premium'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 7.99, GBP: 6.50 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Funimation',
    displayName: 'Funimation',
    category: 'Streaming',
    website: 'https://funimation.com',
    keywords: ['funimation', 'funimation.com', 'funimation*', 'funimation now'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 5.99, GBP: 4.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Tidal',
    displayName: 'Tidal',
    category: 'Streaming',
    website: 'https://tidal.com',
    keywords: ['tidal', 'tidal.com', 'tidal*', 'tidal hifi', 'tidal premium'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 9.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'SoundCloud',
    displayName: 'SoundCloud Go',
    category: 'Streaming',
    website: 'https://soundcloud.com',
    keywords: ['soundcloud', 'soundcloud.com', 'soundcloud*', 'soundcloud go', 'soundcloud go+'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 4.99, GBP: 4.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Deezer',
    displayName: 'Deezer',
    category: 'Streaming',
    website: 'https://deezer.com',
    keywords: ['deezer', 'deezer.com', 'deezer*', 'deezer premium'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 9.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Qobuz',
    displayName: 'Qobuz',
    category: 'Streaming',
    website: 'https://qobuz.com',
    keywords: ['qobuz', 'qobuz.com', 'qobuz*', 'qobuz sublime'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 10.83, GBP: 9.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Apple Music',
    displayName: 'Apple Music',
    category: 'Streaming',
    website: 'https://music.apple.com',
    keywords: ['apple music', 'applemusic', 'apple.com/bill', 'itunes', 'apple*music'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 10.99, GBP: 10.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Amazon Music Unlimited',
    displayName: 'Amazon Music Unlimited',
    category: 'Streaming',
    website: 'https://music.amazon.com',
    keywords: ['amazon music', 'amazon music unlimited', 'amzn.com/bill', 'amazon*music'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 8.99, GBP: 8.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Shudder',
    displayName: 'Shudder',
    category: 'Streaming',
    website: 'https://shudder.com',
    keywords: ['shudder', 'shudder.com', 'shudder*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 5.99, GBP: 4.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Mubi',
    displayName: 'Mubi',
    category: 'Streaming',
    website: 'https://mubi.com',
    keywords: ['mubi', 'mubi.com', 'mubi*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 10.99, GBP: 9.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Criterion Channel',
    displayName: 'Criterion Channel',
    category: 'Streaming',
    website: 'https://criterionchannel.com',
    keywords: ['criterion', 'criterion channel', 'criterionchannel', 'criterion*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 10.99, GBP: 9.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'FuboTV',
    displayName: 'FuboTV',
    category: 'Streaming',
    website: 'https://fubo.tv',
    keywords: ['fubo', 'fubotv', 'fubo tv', 'fubo.tv', 'fubo*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 74.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Sling TV',
    displayName: 'Sling TV',
    category: 'Streaming',
    website: 'https://sling.com',
    keywords: ['sling', 'sling tv', 'slingtv', 'sling.com', 'sling*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 35.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Philo',
    displayName: 'Philo',
    category: 'Streaming',
    website: 'https://philo.com',
    keywords: ['philo', 'philo.com', 'philo*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 25.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'ESPN Plus',
    displayName: 'ESPN+',
    category: 'Streaming',
    website: 'https://espn.com/watch',
    keywords: ['espn', 'espn+', 'espn plus', 'espnplus', 'espn*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 10.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Showtime',
    displayName: 'Showtime',
    category: 'Streaming',
    website: 'https://showtime.com',
    keywords: ['showtime', 'showtime.com', 'showtime*', 'showtime anytime'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 10.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Starz',
    displayName: 'Starz',
    category: 'Streaming',
    website: 'https://starz.com',
    keywords: ['starz', 'starz.com', 'starz*', 'starz play'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 8.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'AMC Plus',
    displayName: 'AMC+',
    category: 'Streaming',
    website: 'https://amcplus.com',
    keywords: ['amc', 'amc+', 'amc plus', 'amcplus', 'amc*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 8.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Audible',
    displayName: 'Audible',
    category: 'Streaming',
    website: 'https://audible.com',
    keywords: ['audible', 'audible.com', 'audible*', 'amzn.com/bill*audible', 'amazon audible'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 14.95, GBP: 7.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Kindle Unlimited',
    displayName: 'Kindle Unlimited',
    category: 'Streaming',
    website: 'https://amazon.com/kindle-dbs',
    keywords: ['kindle unlimited', 'kindleunlimited', 'amzn.com/bill*kindle', 'amazon kindle'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 9.49 },
    billingCycles: ['monthly', 'yearly'],
  },

  // ============================================
  // SOFTWARE SERVICES (40)
  // ============================================
  {
    name: 'Microsoft 365',
    displayName: 'Microsoft 365',
    category: 'Software',
    website: 'https://microsoft.com/microsoft-365',
    keywords: ['microsoft', 'microsoft 365', 'microsoft365', 'office 365', 'office365', 'msft*', 'microsoft*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 6.99, GBP: 5.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Adobe Creative Cloud',
    displayName: 'Adobe Creative Cloud',
    category: 'Software',
    website: 'https://adobe.com/creativecloud',
    keywords: ['adobe', 'adobe creative cloud', 'adobe cc', 'creative cloud', 'adobe*', 'adobe.com'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 52.99, GBP: 49.94 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Notion',
    displayName: 'Notion',
    category: 'Software',
    website: 'https://notion.so',
    keywords: ['notion', 'notion.so', 'notion*', 'notion inc'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 8.00, GBP: 6.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Slack',
    displayName: 'Slack',
    category: 'Software',
    website: 'https://slack.com',
    keywords: ['slack', 'slack.com', 'slack*', 'slack technologies'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 7.25, GBP: 5.75 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Zoom',
    displayName: 'Zoom',
    category: 'Software',
    website: 'https://zoom.us',
    keywords: ['zoom', 'zoom.us', 'zoom*', 'zoom video', 'zoom communications'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 14.99, GBP: 11.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Dropbox',
    displayName: 'Dropbox',
    category: 'Software',
    website: 'https://dropbox.com',
    keywords: ['dropbox', 'dropbox.com', 'dropbox*', 'dropbox inc'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 7.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Google Workspace',
    displayName: 'Google Workspace',
    category: 'Software',
    website: 'https://workspace.google.com',
    keywords: ['google workspace', 'google*workspace', 'g suite', 'gsuite', 'google*', 'google.com'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 6.00, GBP: 4.60 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'GitHub',
    displayName: 'GitHub',
    category: 'Software',
    website: 'https://github.com',
    keywords: ['github', 'github.com', 'github*', 'github inc'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 4.00, GBP: 3.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Figma',
    displayName: 'Figma',
    category: 'Software',
    website: 'https://figma.com',
    keywords: ['figma', 'figma.com', 'figma*', 'figma inc'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 12.00, GBP: 10.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Canva Pro',
    displayName: 'Canva Pro',
    category: 'Software',
    website: 'https://canva.com',
    keywords: ['canva', 'canva.com', 'canva*', 'canva pro'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 12.99, GBP: 10.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Grammarly',
    displayName: 'Grammarly',
    category: 'Software',
    website: 'https://grammarly.com',
    keywords: ['grammarly', 'grammarly.com', 'grammarly*', 'grammarly inc'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 12.00, GBP: 10.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'ChatGPT Plus',
    displayName: 'ChatGPT Plus',
    category: 'Software',
    website: 'https://chat.openai.com',
    keywords: ['chatgpt', 'openai', 'chatgpt plus', 'openai*', 'chat.openai.com'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 20.00, GBP: 16.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Midjourney',
    displayName: 'Midjourney',
    category: 'Software',
    website: 'https://midjourney.com',
    keywords: ['midjourney', 'midjourney.com', 'midjourney*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 10.00, GBP: 8.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Todoist',
    displayName: 'Todoist',
    category: 'Software',
    website: 'https://todoist.com',
    keywords: ['todoist', 'todoist.com', 'todoist*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 4.00, GBP: 3.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Evernote',
    displayName: 'Evernote',
    category: 'Software',
    website: 'https://evernote.com',
    keywords: ['evernote', 'evernote.com', 'evernote*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 7.99, GBP: 6.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: '1Password',
    displayName: '1Password',
    category: 'Software',
    website: 'https://1password.com',
    keywords: ['1password', '1password.com', '1password*', 'one password'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 2.99, GBP: 2.50 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'LastPass',
    displayName: 'LastPass',
    category: 'Software',
    website: 'https://lastpass.com',
    keywords: ['lastpass', 'lastpass.com', 'lastpass*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 3.00, GBP: 2.50 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Dashlane',
    displayName: 'Dashlane',
    category: 'Software',
    website: 'https://dashlane.com',
    keywords: ['dashlane', 'dashlane.com', 'dashlane*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 4.99, GBP: 3.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'NordVPN',
    displayName: 'NordVPN',
    category: 'Software',
    website: 'https://nordvpn.com',
    keywords: ['nordvpn', 'nordvpn.com', 'nordvpn*', 'nord vpn'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 11.95, GBP: 9.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'ExpressVPN',
    displayName: 'ExpressVPN',
    category: 'Software',
    website: 'https://expressvpn.com',
    keywords: ['expressvpn', 'expressvpn.com', 'expressvpn*', 'express vpn'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 12.95, GBP: 10.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Surfshark',
    displayName: 'Surfshark',
    category: 'Software',
    website: 'https://surfshark.com',
    keywords: ['surfshark', 'surfshark.com', 'surfshark*', 'surf shark'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 12.95, GBP: 10.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'ProtonVPN',
    displayName: 'ProtonVPN',
    category: 'Software',
    website: 'https://protonvpn.com',
    keywords: ['protonvpn', 'protonvpn.com', 'protonvpn*', 'proton vpn'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 7.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'ProtonMail',
    displayName: 'ProtonMail',
    category: 'Software',
    website: 'https://proton.me',
    keywords: ['protonmail', 'protonmail.com', 'protonmail*', 'proton mail', 'proton.me'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 4.99, GBP: 3.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Linear',
    displayName: 'Linear',
    category: 'Software',
    website: 'https://linear.app',
    keywords: ['linear', 'linear.app', 'linear*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 8.00, GBP: 6.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Asana',
    displayName: 'Asana',
    category: 'Software',
    website: 'https://asana.com',
    keywords: ['asana', 'asana.com', 'asana*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 10.99, GBP: 8.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Monday.com',
    displayName: 'Monday.com',
    category: 'Software',
    website: 'https://monday.com',
    keywords: ['monday', 'monday.com', 'monday*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 8.00, GBP: 6.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Trello',
    displayName: 'Trello',
    category: 'Software',
    website: 'https://trello.com',
    keywords: ['trello', 'trello.com', 'trello*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 5.00, GBP: 4.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Airtable',
    displayName: 'Airtable',
    category: 'Software',
    website: 'https://airtable.com',
    keywords: ['airtable', 'airtable.com', 'airtable*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 10.00, GBP: 8.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'ClickUp',
    displayName: 'ClickUp',
    category: 'Software',
    website: 'https://clickup.com',
    keywords: ['clickup', 'clickup.com', 'clickup*', 'click up'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 5.00, GBP: 4.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Obsidian',
    displayName: 'Obsidian',
    category: 'Software',
    website: 'https://obsidian.md',
    keywords: ['obsidian', 'obsidian.md', 'obsidian*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 8.00, GBP: 6.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Roam Research',
    displayName: 'Roam Research',
    category: 'Software',
    website: 'https://roamresearch.com',
    keywords: ['roam', 'roam research', 'roamresearch', 'roam*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 15.00, GBP: 12.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Bear',
    displayName: 'Bear',
    category: 'Software',
    website: 'https://bear.app',
    keywords: ['bear', 'bear.app', 'bear*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 1.49, GBP: 1.49 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Ulysses',
    displayName: 'Ulysses',
    category: 'Software',
    website: 'https://ulysses.app',
    keywords: ['ulysses', 'ulysses.app', 'ulysses*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 5.99, GBP: 4.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Setapp',
    displayName: 'Setapp',
    category: 'Software',
    website: 'https://setapp.com',
    keywords: ['setapp', 'setapp.com', 'setapp*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 8.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'CleanMyMac',
    displayName: 'CleanMyMac',
    category: 'Software',
    website: 'https://macpaw.com',
    keywords: ['cleanmymac', 'cleanmymac*', 'macpaw', 'macpaw.com'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 7.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Parallels',
    displayName: 'Parallels Desktop',
    category: 'Software',
    website: 'https://parallels.com',
    keywords: ['parallels', 'parallels.com', 'parallels*', 'parallels desktop'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 99.99, GBP: 79.99 },
    billingCycles: ['yearly'],
  },
  {
    name: 'VMware Fusion',
    displayName: 'VMware Fusion',
    category: 'Software',
    website: 'https://vmware.com',
    keywords: ['vmware', 'vmware.com', 'vmware*', 'vmware fusion'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 79.99, GBP: 64.99 },
    billingCycles: ['yearly'],
  },
  {
    name: 'JetBrains',
    displayName: 'JetBrains',
    category: 'Software',
    website: 'https://jetbrains.com',
    keywords: ['jetbrains', 'jetbrains.com', 'jetbrains*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 8.90, GBP: 7.20 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'CodeSandbox',
    displayName: 'CodeSandbox',
    category: 'Software',
    website: 'https://codesandbox.io',
    keywords: ['codesandbox', 'codesandbox.io', 'codesandbox*', 'code sandbox'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 7.00, GBP: 5.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Replit',
    displayName: 'Replit',
    category: 'Software',
    website: 'https://replit.com',
    keywords: ['replit', 'replit.com', 'replit*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 7.00, GBP: 5.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Vercel',
    displayName: 'Vercel',
    category: 'Software',
    website: 'https://vercel.com',
    keywords: ['vercel', 'vercel.com', 'vercel*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 20.00, GBP: 16.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Netlify',
    displayName: 'Netlify',
    category: 'Software',
    website: 'https://netlify.com',
    keywords: ['netlify', 'netlify.com', 'netlify*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 19.00, GBP: 15.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Heroku',
    displayName: 'Heroku',
    category: 'Software',
    website: 'https://heroku.com',
    keywords: ['heroku', 'heroku.com', 'heroku*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 7.00, GBP: 5.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'DigitalOcean',
    displayName: 'DigitalOcean',
    category: 'Software',
    website: 'https://digitalocean.com',
    keywords: ['digitalocean', 'digitalocean.com', 'digitalocean*', 'digital ocean'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 6.00, GBP: 4.50 },
    billingCycles: ['monthly'],
  },

  // ============================================
  // GAMING SERVICES (20)
  // ============================================
  {
    name: 'Xbox Game Pass',
    displayName: 'Xbox Game Pass',
    category: 'Gaming',
    website: 'https://xbox.com/gamepass',
    keywords: ['xbox', 'xbox game pass', 'xboxgamepass', 'microsoft*xbox', 'xbox*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 7.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'PlayStation Plus',
    displayName: 'PlayStation Plus',
    category: 'Gaming',
    website: 'https://playstation.com/plus',
    keywords: ['playstation', 'playstation plus', 'playstationplus', 'ps plus', 'psplus', 'sony*playstation'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 6.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Nintendo Switch Online',
    displayName: 'Nintendo Switch Online',
    category: 'Gaming',
    website: 'https://nintendo.com/switch/online',
    keywords: ['nintendo', 'nintendo switch', 'nintendo switch online', 'nintendo*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 3.99, GBP: 3.49 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'EA Play',
    displayName: 'EA Play',
    category: 'Gaming',
    website: 'https://ea.com/ea-play',
    keywords: ['ea play', 'eaplay', 'electronic arts', 'ea*', 'origin access'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 4.99, GBP: 3.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Ubisoft Plus',
    displayName: 'Ubisoft+',
    category: 'Gaming',
    website: 'https://ubisoft.com/plus',
    keywords: ['ubisoft', 'ubisoft+', 'ubisoft plus', 'ubisoftplus', 'ubisoft*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 14.99, GBP: 12.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Apple Arcade',
    displayName: 'Apple Arcade',
    category: 'Gaming',
    website: 'https://apple.com/apple-arcade',
    keywords: ['apple arcade', 'applearcade', 'apple.com/bill*arcade', 'apple*arcade'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 4.99, GBP: 4.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Google Play Pass',
    displayName: 'Google Play Pass',
    category: 'Gaming',
    website: 'https://play.google.com/about/play-pass',
    keywords: ['google play pass', 'google*play pass', 'play pass', 'google*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 4.99, GBP: 4.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Discord Nitro',
    displayName: 'Discord Nitro',
    category: 'Gaming',
    website: 'https://discord.com/nitro',
    keywords: ['discord', 'discord nitro', 'discord.com', 'discord*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 8.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Twitch Turbo',
    displayName: 'Twitch Turbo',
    category: 'Gaming',
    website: 'https://twitch.tv/turbo',
    keywords: ['twitch', 'twitch turbo', 'twitch.tv', 'twitch*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 8.99, GBP: 7.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Steam',
    displayName: 'Steam',
    category: 'Gaming',
    website: 'https://steampowered.com',
    keywords: ['steam', 'steampowered', 'steam*', 'valve'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 4.99, GBP: 3.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'GeForce Now',
    displayName: 'GeForce Now',
    category: 'Gaming',
    website: 'https://nvidia.com/geforce-now',
    keywords: ['geforce now', 'geforcenow', 'nvidia geforce', 'nvidia*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 8.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Xbox Live Gold',
    displayName: 'Xbox Live Gold',
    category: 'Gaming',
    website: 'https://xbox.com/live',
    keywords: ['xbox live', 'xboxlive', 'xbox live gold', 'microsoft*xbox live'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 6.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'World of Warcraft',
    displayName: 'World of Warcraft',
    category: 'Gaming',
    website: 'https://worldofwarcraft.com',
    keywords: ['wow', 'world of warcraft', 'blizzard', 'blizzard*wow'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 14.99, GBP: 9.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Final Fantasy XIV',
    displayName: 'Final Fantasy XIV',
    category: 'Gaming',
    website: 'https://finalfantasyxiv.com',
    keywords: ['ffxiv', 'final fantasy xiv', 'final fantasy 14', 'square enix'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 12.99, GBP: 7.69 },
    billingCycles: ['monthly'],
  },
  {
    name: 'EVE Online',
    displayName: 'EVE Online',
    category: 'Gaming',
    website: 'https://eveonline.com',
    keywords: ['eve online', 'eveonline', 'ccp games'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 14.95, GBP: 9.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Star Citizen',
    displayName: 'Star Citizen',
    category: 'Gaming',
    website: 'https://robertsspaceindustries.com',
    keywords: ['star citizen', 'star citizen*', 'roberts space industries'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 10.00, GBP: 8.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Roblox Premium',
    displayName: 'Roblox Premium',
    category: 'Gaming',
    website: 'https://roblox.com',
    keywords: ['roblox', 'roblox premium', 'roblox.com', 'roblox*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 4.99, GBP: 3.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Minecraft Realms',
    displayName: 'Minecraft Realms',
    category: 'Gaming',
    website: 'https://minecraft.net',
    keywords: ['minecraft', 'minecraft realms', 'minecraft*', 'mojang'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 7.99, GBP: 6.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Epic Games',
    displayName: 'Epic Games',
    category: 'Gaming',
    website: 'https://epicgames.com',
    keywords: ['epic games', 'epicgames', 'epic*', 'epic store'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 7.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Origin Access',
    displayName: 'Origin Access',
    category: 'Gaming',
    website: 'https://ea.com',
    keywords: ['origin', 'origin access', 'origin*', 'electronic arts origin'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 4.99, GBP: 3.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Stadia',
    displayName: 'Google Stadia',
    category: 'Gaming',
    website: 'https://stadia.google.com',
    keywords: ['stadia', 'google stadia', 'stadia*', 'google*stadia'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 8.99 },
    billingCycles: ['monthly'],
  },

  // ============================================
  // NEWS & MEDIA (25)
  // ============================================
  {
    name: 'The New York Times',
    displayName: 'The New York Times',
    category: 'News & Media',
    website: 'https://nytimes.com',
    keywords: ['new york times', 'nytimes', 'ny times', 'nytimes.com', 'nytimes*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 17.00, GBP: 12.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Wall Street Journal',
    displayName: 'Wall Street Journal',
    category: 'News & Media',
    website: 'https://wsj.com',
    keywords: ['wall street journal', 'wsj', 'wsj.com', 'wsj*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 38.99, GBP: 29.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'The Guardian',
    displayName: 'The Guardian',
    category: 'News & Media',
    website: 'https://theguardian.com',
    keywords: ['guardian', 'the guardian', 'guardian.com', 'guardian*'],
    countries: ['UK', 'US'],
    currency: ['GBP', 'USD'],
    typicalAmounts: { GBP: 6.99, USD: 9.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'The Times',
    displayName: 'The Times',
    category: 'News & Media',
    website: 'https://thetimes.co.uk',
    keywords: ['the times', 'times', 'thetimes', 'times.co.uk', 'times*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 26.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Financial Times',
    displayName: 'Financial Times',
    category: 'News & Media',
    website: 'https://ft.com',
    keywords: ['financial times', 'ft', 'ft.com', 'ft*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 39.00, GBP: 29.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Washington Post',
    displayName: 'Washington Post',
    category: 'News & Media',
    website: 'https://washingtonpost.com',
    keywords: ['washington post', 'wapo', 'washingtonpost.com', 'wapo*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 10.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'The Economist',
    displayName: 'The Economist',
    category: 'News & Media',
    website: 'https://economist.com',
    keywords: ['economist', 'the economist', 'economist.com', 'economist*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 22.00, GBP: 16.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'New Yorker',
    displayName: 'The New Yorker',
    category: 'News & Media',
    website: 'https://newyorker.com',
    keywords: ['new yorker', 'newyorker', 'newyorker.com', 'newyorker*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 6.99, GBP: 5.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'The Atlantic',
    displayName: 'The Atlantic',
    category: 'News & Media',
    website: 'https://theatlantic.com',
    keywords: ['atlantic', 'the atlantic', 'theatlantic.com', 'atlantic*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 49.99, GBP: 39.99 },
    billingCycles: ['yearly'],
  },
  {
    name: 'Wired',
    displayName: 'Wired',
    category: 'News & Media',
    website: 'https://wired.com',
    keywords: ['wired', 'wired.com', 'wired*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 5.00, GBP: 4.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Medium',
    displayName: 'Medium',
    category: 'News & Media',
    website: 'https://medium.com',
    keywords: ['medium', 'medium.com', 'medium*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 5.00, GBP: 4.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Substack',
    displayName: 'Substack',
    category: 'News & Media',
    website: 'https://substack.com',
    keywords: ['substack', 'substack.com', 'substack*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 5.00, GBP: 4.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Patreon',
    displayName: 'Patreon',
    category: 'News & Media',
    website: 'https://patreon.com',
    keywords: ['patreon', 'patreon.com', 'patreon*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 5.00, GBP: 4.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'OnlyFans',
    displayName: 'OnlyFans',
    category: 'News & Media',
    website: 'https://onlyfans.com',
    keywords: ['onlyfans', 'onlyfans.com', 'onlyfans*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 4.99, GBP: 4.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Blinkist',
    displayName: 'Blinkist',
    category: 'News & Media',
    website: 'https://blinkist.com',
    keywords: ['blinkist', 'blinkist.com', 'blinkist*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 7.99, GBP: 6.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'MasterClass',
    displayName: 'MasterClass',
    category: 'News & Media',
    website: 'https://masterclass.com',
    keywords: ['masterclass', 'masterclass.com', 'masterclass*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 15.00, GBP: 12.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Skillshare',
    displayName: 'Skillshare',
    category: 'News & Media',
    website: 'https://skillshare.com',
    keywords: ['skillshare', 'skillshare.com', 'skillshare*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 32.00, GBP: 25.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'LinkedIn Learning',
    displayName: 'LinkedIn Learning',
    category: 'News & Media',
    website: 'https://linkedin.com/learning',
    keywords: ['linkedin learning', 'linkedin*learning', 'lynda', 'lynda.com'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 29.99, GBP: 24.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Udemy',
    displayName: 'Udemy',
    category: 'News & Media',
    website: 'https://udemy.com',
    keywords: ['udemy', 'udemy.com', 'udemy*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 16.99, GBP: 12.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Coursera',
    displayName: 'Coursera',
    category: 'News & Media',
    website: 'https://coursera.org',
    keywords: ['coursera', 'coursera.org', 'coursera*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 39.00, GBP: 29.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Khan Academy',
    displayName: 'Khan Academy',
    category: 'News & Media',
    website: 'https://khanacademy.org',
    keywords: ['khan academy', 'khanacademy', 'khanacademy.org', 'khan*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 0.00, GBP: 0.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'The Athletic',
    displayName: 'The Athletic',
    category: 'News & Media',
    website: 'https://theathletic.com',
    keywords: ['athletic', 'the athletic', 'theathletic.com', 'athletic*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 7.99, GBP: 5.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Bloomberg',
    displayName: 'Bloomberg',
    category: 'News & Media',
    website: 'https://bloomberg.com',
    keywords: ['bloomberg', 'bloomberg.com', 'bloomberg*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 34.99, GBP: 24.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Reuters',
    displayName: 'Reuters',
    category: 'News & Media',
    website: 'https://reuters.com',
    keywords: ['reuters', 'reuters.com', 'reuters*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 34.99, GBP: 24.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'BBC iPlayer',
    displayName: 'BBC iPlayer',
    category: 'News & Media',
    website: 'https://bbc.co.uk/iplayer',
    keywords: ['bbc', 'bbc iplayer', 'bbciplayer', 'bbc.co.uk', 'bbc*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 13.25 },
    billingCycles: ['yearly'],
  },

  // ============================================
  // FITNESS SERVICES (15)
  // ============================================
  {
    name: 'Peloton',
    displayName: 'Peloton',
    category: 'Fitness',
    website: 'https://onepeloton.com',
    keywords: ['peloton', 'peloton.com', 'peloton*', 'one peloton'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 12.99, GBP: 9.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Apple Fitness Plus',
    displayName: 'Apple Fitness+',
    category: 'Fitness',
    website: 'https://apple.com/apple-fitness-plus',
    keywords: ['apple fitness', 'apple fitness+', 'applefitness', 'apple.com/bill*fitness', 'apple*fitness'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 7.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'ClassPass',
    displayName: 'ClassPass',
    category: 'Fitness',
    website: 'https://classpass.com',
    keywords: ['classpass', 'classpass.com', 'classpass*', 'class pass'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 15.00, GBP: 12.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Planet Fitness',
    displayName: 'Planet Fitness',
    category: 'Fitness',
    website: 'https://planetfitness.com',
    keywords: ['planet fitness', 'planetfitness', 'planetfitness.com', 'planet fitness*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 10.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'LA Fitness',
    displayName: 'LA Fitness',
    category: 'Fitness',
    website: 'https://lafitness.com',
    keywords: ['la fitness', 'lafitness', 'lafitness.com', 'la fitness*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 29.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Strava',
    displayName: 'Strava',
    category: 'Fitness',
    website: 'https://strava.com',
    keywords: ['strava', 'strava.com', 'strava*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 11.99, GBP: 8.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'MyFitnessPal',
    displayName: 'MyFitnessPal',
    category: 'Fitness',
    website: 'https://myfitnesspal.com',
    keywords: ['myfitnesspal', 'myfitnesspal.com', 'myfitnesspal*', 'my fitness pal'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 7.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Headspace',
    displayName: 'Headspace',
    category: 'Fitness',
    website: 'https://headspace.com',
    keywords: ['headspace', 'headspace.com', 'headspace*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 12.99, GBP: 9.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Calm',
    displayName: 'Calm',
    category: 'Fitness',
    website: 'https://calm.com',
    keywords: ['calm', 'calm.com', 'calm*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 14.99, GBP: 11.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Noom',
    displayName: 'Noom',
    category: 'Fitness',
    website: 'https://noom.com',
    keywords: ['noom', 'noom.com', 'noom*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 60.00, GBP: 45.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Nike Training Club',
    displayName: 'Nike Training Club',
    category: 'Fitness',
    website: 'https://nike.com',
    keywords: ['nike training', 'nike training club', 'nike*', 'nike.com'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 0.00, GBP: 0.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Fitbit Premium',
    displayName: 'Fitbit Premium',
    category: 'Fitness',
    website: 'https://fitbit.com',
    keywords: ['fitbit', 'fitbit premium', 'fitbit.com', 'fitbit*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 7.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Garmin Connect',
    displayName: 'Garmin Connect',
    category: 'Fitness',
    website: 'https://garmin.com',
    keywords: ['garmin', 'garmin connect', 'garmin.com', 'garmin*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 5.99, GBP: 4.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Whoop',
    displayName: 'Whoop',
    category: 'Fitness',
    website: 'https://whoop.com',
    keywords: ['whoop', 'whoop.com', 'whoop*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 30.00, GBP: 24.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Oura Ring',
    displayName: 'Oura Ring',
    category: 'Fitness',
    website: 'https://ouraring.com',
    keywords: ['oura', 'oura ring', 'ouraring', 'ouraring.com', 'oura*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 5.99, GBP: 4.99 },
    billingCycles: ['monthly'],
  },

  // ============================================
  // FOOD DELIVERY (15)
  // ============================================
  {
    name: 'DoorDash',
    displayName: 'DoorDash',
    category: 'Food Delivery',
    website: 'https://doordash.com',
    keywords: ['doordash', 'doordash.com', 'doordash*', 'door dash'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 7.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Uber Eats',
    displayName: 'Uber Eats',
    category: 'Food Delivery',
    website: 'https://ubereats.com',
    keywords: ['uber eats', 'ubereats', 'ubereats.com', 'uber*eats'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 7.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Grubhub Plus',
    displayName: 'Grubhub+',
    category: 'Food Delivery',
    website: 'https://grubhub.com',
    keywords: ['grubhub', 'grubhub+', 'grubhub plus', 'grubhub.com', 'grubhub*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 9.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Deliveroo Plus',
    displayName: 'Deliveroo Plus',
    category: 'Food Delivery',
    website: 'https://deliveroo.co.uk',
    keywords: ['deliveroo', 'deliveroo plus', 'deliveroo.co.uk', 'deliveroo*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 7.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Instacart Plus',
    displayName: 'Instacart+',
    category: 'Food Delivery',
    website: 'https://instacart.com',
    keywords: ['instacart', 'instacart+', 'instacart plus', 'instacart.com', 'instacart*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 9.99, GBP: 7.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Amazon Fresh',
    displayName: 'Amazon Fresh',
    category: 'Food Delivery',
    website: 'https://amazon.com/fresh',
    keywords: ['amazon fresh', 'amazonfresh', 'amzn.com/bill*fresh', 'amazon*fresh'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 14.99, GBP: 7.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'HelloFresh',
    displayName: 'HelloFresh',
    category: 'Food Delivery',
    website: 'https://hellofresh.com',
    keywords: ['hellofresh', 'hellofresh.com', 'hellofresh*', 'hello fresh'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 59.94, GBP: 44.99 },
    billingCycles: ['weekly'],
  },
  {
    name: 'Blue Apron',
    displayName: 'Blue Apron',
    category: 'Food Delivery',
    website: 'https://blueapron.com',
    keywords: ['blue apron', 'blueapron', 'blueapron.com', 'blue apron*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 59.94 },
    billingCycles: ['weekly'],
  },
  {
    name: 'Home Chef',
    displayName: 'Home Chef',
    category: 'Food Delivery',
    website: 'https://homechef.com',
    keywords: ['home chef', 'homechef', 'homechef.com', 'home chef*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 59.94 },
    billingCycles: ['weekly'],
  },
  {
    name: 'Freshly',
    displayName: 'Freshly',
    category: 'Food Delivery',
    website: 'https://freshly.com',
    keywords: ['freshly', 'freshly.com', 'freshly*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 59.99 },
    billingCycles: ['weekly'],
  },
  {
    name: 'EveryPlate',
    displayName: 'EveryPlate',
    category: 'Food Delivery',
    website: 'https://everyplate.com',
    keywords: ['everyplate', 'everyplate.com', 'everyplate*', 'every plate'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 48.93 },
    billingCycles: ['weekly'],
  },
  {
    name: 'Marley Spoon',
    displayName: 'Marley Spoon',
    category: 'Food Delivery',
    website: 'https://marleyspoon.com',
    keywords: ['marley spoon', 'marleyspoon', 'marleyspoon.com', 'marley spoon*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 59.94, GBP: 44.99 },
    billingCycles: ['weekly'],
  },
  {
    name: 'Gousto',
    displayName: 'Gousto',
    category: 'Food Delivery',
    website: 'https://gousto.co.uk',
    keywords: ['gousto', 'gousto.co.uk', 'gousto*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 44.99 },
    billingCycles: ['weekly'],
  },
  {
    name: 'Mindful Chef',
    displayName: 'Mindful Chef',
    category: 'Food Delivery',
    website: 'https://mindfulchef.com',
    keywords: ['mindful chef', 'mindfulchef', 'mindfulchef.com', 'mindful chef*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 49.99 },
    billingCycles: ['weekly'],
  },
  {
    name: 'Riverford',
    displayName: 'Riverford',
    category: 'Food Delivery',
    website: 'https://riverford.co.uk',
    keywords: ['riverford', 'riverford.co.uk', 'riverford*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 24.95 },
    billingCycles: ['weekly'],
  },

  // ============================================
  // CLOUD STORAGE (10)
  // ============================================
  {
    name: 'iCloud',
    displayName: 'iCloud',
    category: 'Cloud Storage',
    website: 'https://icloud.com',
    keywords: ['icloud', 'icloud.com', 'icloud*', 'apple.com/bill*icloud', 'apple*icloud'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 0.99, GBP: 0.79 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Google One',
    displayName: 'Google One',
    category: 'Cloud Storage',
    website: 'https://one.google.com',
    keywords: ['google one', 'google*one', 'google drive', 'google*drive'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 1.99, GBP: 1.59 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'OneDrive',
    displayName: 'Microsoft OneDrive',
    category: 'Cloud Storage',
    website: 'https://onedrive.live.com',
    keywords: ['onedrive', 'one drive', 'onedrive.live.com', 'microsoft*onedrive', 'msft*onedrive'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 1.99, GBP: 1.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Box',
    displayName: 'Box',
    category: 'Cloud Storage',
    website: 'https://box.com',
    keywords: ['box', 'box.com', 'box*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 5.00, GBP: 4.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'pCloud',
    displayName: 'pCloud',
    category: 'Cloud Storage',
    website: 'https://pcloud.com',
    keywords: ['pcloud', 'pcloud.com', 'pcloud*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 4.99, GBP: 3.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Sync.com',
    displayName: 'Sync.com',
    category: 'Cloud Storage',
    website: 'https://sync.com',
    keywords: ['sync.com', 'sync*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 5.00, GBP: 4.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Tresorit',
    displayName: 'Tresorit',
    category: 'Cloud Storage',
    website: 'https://tresorit.com',
    keywords: ['tresorit', 'tresorit.com', 'tresorit*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 10.42, GBP: 8.33 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Mega',
    displayName: 'MEGA',
    category: 'Cloud Storage',
    website: 'https://mega.nz',
    keywords: ['mega', 'mega.nz', 'mega*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 4.99, GBP: 3.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Backblaze',
    displayName: 'Backblaze',
    category: 'Cloud Storage',
    website: 'https://backblaze.com',
    keywords: ['backblaze', 'backblaze.com', 'backblaze*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 7.00, GBP: 5.50 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Carbonite',
    displayName: 'Carbonite',
    category: 'Cloud Storage',
    website: 'https://carbonite.com',
    keywords: ['carbonite', 'carbonite.com', 'carbonite*'],
    countries: ['US', 'UK'],
    currency: ['USD', 'GBP'],
    typicalAmounts: { USD: 6.00, GBP: 4.50 },
    billingCycles: ['monthly', 'yearly'],
  },

  // ============================================
  // UK SPECIFIC (20)
  // ============================================
  {
    name: 'Sky',
    displayName: 'Sky',
    category: 'Streaming',
    website: 'https://sky.com',
    keywords: ['sky', 'sky.com', 'sky*', 'sky tv', 'sky broadband'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 26.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'BT Sport',
    displayName: 'BT Sport',
    category: 'Streaming',
    website: 'https://bt.com/sport',
    keywords: ['bt sport', 'btsport', 'bt.com', 'bt*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 25.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'NOW TV',
    displayName: 'NOW TV',
    category: 'Streaming',
    website: 'https://nowtv.com',
    keywords: ['now tv', 'nowtv', 'nowtv.com', 'now tv*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 9.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'ITV Hub',
    displayName: 'ITV Hub',
    category: 'Streaming',
    website: 'https://itv.com',
    keywords: ['itv hub', 'itvhub', 'itv.com', 'itv*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 3.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Channel 4',
    displayName: 'Channel 4',
    category: 'Streaming',
    website: 'https://channel4.com',
    keywords: ['channel 4', 'channel4', 'channel4.com', 'channel 4*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 3.99 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Virgin Media',
    displayName: 'Virgin Media',
    category: 'Streaming',
    website: 'https://virginmedia.com',
    keywords: ['virgin media', 'virginmedia', 'virginmedia.com', 'virgin media*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 30.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'TalkTalk',
    displayName: 'TalkTalk',
    category: 'Streaming',
    website: 'https://talktalk.co.uk',
    keywords: ['talktalk', 'talktalk.co.uk', 'talktalk*', 'talk talk'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 25.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'EE',
    displayName: 'EE',
    category: 'Streaming',
    website: 'https://ee.co.uk',
    keywords: ['ee', 'ee.co.uk', 'ee*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 20.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'O2',
    displayName: 'O2',
    category: 'Streaming',
    website: 'https://o2.co.uk',
    keywords: ['o2', 'o2.co.uk', 'o2*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 20.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Three',
    displayName: 'Three',
    category: 'Streaming',
    website: 'https://three.co.uk',
    keywords: ['three', 'three.co.uk', 'three*', '3'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 20.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Tesco Mobile',
    displayName: 'Tesco Mobile',
    category: 'Streaming',
    website: 'https://tescomobile.com',
    keywords: ['tesco mobile', 'tescomobile', 'tescomobile.com', 'tesco mobile*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 15.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Sainsburys',
    displayName: 'Sainsbury\'s',
    category: 'Food Delivery',
    website: 'https://sainsburys.co.uk',
    keywords: ['sainsburys', 'sainsburys.co.uk', 'sainsburys*', 'sainsbury\'s'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 0.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Boots',
    displayName: 'Boots',
    category: 'Food Delivery',
    website: 'https://boots.com',
    keywords: ['boots', 'boots.com', 'boots*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 0.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Ocado',
    displayName: 'Ocado',
    category: 'Food Delivery',
    website: 'https://ocado.com',
    keywords: ['ocado', 'ocado.com', 'ocado*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 0.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Waitrose',
    displayName: 'Waitrose',
    category: 'Food Delivery',
    website: 'https://waitrose.com',
    keywords: ['waitrose', 'waitrose.com', 'waitrose*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 0.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'ASDA',
    displayName: 'ASDA',
    category: 'Food Delivery',
    website: 'https://asda.com',
    keywords: ['asda', 'asda.com', 'asda*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 0.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Morrisons',
    displayName: 'Morrisons',
    category: 'Food Delivery',
    website: 'https://morrisons.com',
    keywords: ['morrisons', 'morrisons.com', 'morrisons*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 0.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Marks & Spencer',
    displayName: 'Marks & Spencer',
    category: 'Food Delivery',
    website: 'https://marksandspencer.com',
    keywords: ['marks & spencer', 'marksandspencer', 'm&s', 'marks and spencer'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 0.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Co-op',
    displayName: 'Co-op',
    category: 'Food Delivery',
    website: 'https://coop.co.uk',
    keywords: ['co-op', 'coop', 'coop.co.uk', 'co-op*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 0.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Iceland',
    displayName: 'Iceland',
    category: 'Food Delivery',
    website: 'https://iceland.co.uk',
    keywords: ['iceland', 'iceland.co.uk', 'iceland*'],
    countries: ['UK'],
    currency: ['GBP'],
    typicalAmounts: { GBP: 0.00 },
    billingCycles: ['monthly'],
  },

  // ============================================
  // US SPECIFIC (25)
  // ============================================
  {
    name: 'AT&T',
    displayName: 'AT&T',
    category: 'Streaming',
    website: 'https://att.com',
    keywords: ['at&t', 'att', 'att.com', 'at&t*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 50.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Verizon',
    displayName: 'Verizon',
    category: 'Streaming',
    website: 'https://verizon.com',
    keywords: ['verizon', 'verizon.com', 'verizon*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 50.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'T-Mobile',
    displayName: 'T-Mobile',
    category: 'Streaming',
    website: 'https://t-mobile.com',
    keywords: ['t-mobile', 'tmobile', 't-mobile.com', 't-mobile*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 50.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Comcast',
    displayName: 'Comcast Xfinity',
    category: 'Streaming',
    website: 'https://xfinity.com',
    keywords: ['comcast', 'xfinity', 'xfinity.com', 'comcast*', 'xfinity*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 50.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Spectrum',
    displayName: 'Spectrum',
    category: 'Streaming',
    website: 'https://spectrum.com',
    keywords: ['spectrum', 'spectrum.com', 'spectrum*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 50.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Cox',
    displayName: 'Cox',
    category: 'Streaming',
    website: 'https://cox.com',
    keywords: ['cox', 'cox.com', 'cox*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 50.00 },
    billingCycles: ['monthly'],
  },
  {
    name: 'Sirius XM',
    displayName: 'SiriusXM',
    category: 'Streaming',
    website: 'https://siriusxm.com',
    keywords: ['sirius', 'sirius xm', 'siriusxm', 'siriusxm.com', 'sirius*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 10.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Pandora Plus',
    displayName: 'Pandora Plus',
    category: 'Streaming',
    website: 'https://pandora.com',
    keywords: ['pandora plus', 'pandoraplus', 'pandora.com', 'pandora*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 4.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Apple News Plus',
    displayName: 'Apple News+',
    category: 'News & Media',
    website: 'https://apple.com/apple-news',
    keywords: ['apple news', 'apple news+', 'applenews', 'apple.com/bill*news', 'apple*news'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 9.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Texture',
    displayName: 'Texture',
    category: 'News & Media',
    website: 'https://texture.com',
    keywords: ['texture', 'texture.com', 'texture*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 9.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Newsday',
    displayName: 'Newsday',
    category: 'News & Media',
    website: 'https://newsday.com',
    keywords: ['newsday', 'newsday.com', 'newsday*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 5.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Los Angeles Times',
    displayName: 'Los Angeles Times',
    category: 'News & Media',
    website: 'https://latimes.com',
    keywords: ['los angeles times', 'latimes', 'latimes.com', 'la times'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 1.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Chicago Tribune',
    displayName: 'Chicago Tribune',
    category: 'News & Media',
    website: 'https://chicagotribune.com',
    keywords: ['chicago tribune', 'chicagotribune', 'chicagotribune.com', 'chicago tribune*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 1.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Boston Globe',
    displayName: 'Boston Globe',
    category: 'News & Media',
    website: 'https://bostonglobe.com',
    keywords: ['boston globe', 'bostonglobe', 'bostonglobe.com', 'boston globe*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 1.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'USA Today',
    displayName: 'USA Today',
    category: 'News & Media',
    website: 'https://usatoday.com',
    keywords: ['usa today', 'usatoday', 'usatoday.com', 'usa today*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 1.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'The Daily Beast',
    displayName: 'The Daily Beast',
    category: 'News & Media',
    website: 'https://thedailybeast.com',
    keywords: ['daily beast', 'thedailybeast', 'thedailybeast.com', 'daily beast*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 4.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Politico',
    displayName: 'Politico',
    category: 'News & Media',
    website: 'https://politico.com',
    keywords: ['politico', 'politico.com', 'politico*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 1.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Axios',
    displayName: 'Axios',
    category: 'News & Media',
    website: 'https://axios.com',
    keywords: ['axios', 'axios.com', 'axios*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 1.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'The Information',
    displayName: 'The Information',
    category: 'News & Media',
    website: 'https://theinformation.com',
    keywords: ['the information', 'theinformation', 'theinformation.com', 'the information*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 39.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Stratechery',
    displayName: 'Stratechery',
    category: 'News & Media',
    website: 'https://stratechery.com',
    keywords: ['stratechery', 'stratechery.com', 'stratechery*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 12.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'The Ringer',
    displayName: 'The Ringer',
    category: 'News & Media',
    website: 'https://theringer.com',
    keywords: ['ringer', 'the ringer', 'theringer', 'theringer.com', 'ringer*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 5.00 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'The Athletic',
    displayName: 'The Athletic',
    category: 'News & Media',
    website: 'https://theathletic.com',
    keywords: ['athletic', 'the athletic', 'theathletic.com', 'athletic*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 7.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Bleacher Report',
    displayName: 'Bleacher Report',
    category: 'News & Media',
    website: 'https://bleacherreport.com',
    keywords: ['bleacher report', 'bleacherreport', 'bleacherreport.com', 'bleacher report*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 9.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'ESPN Insider',
    displayName: 'ESPN Insider',
    category: 'News & Media',
    website: 'https://espn.com',
    keywords: ['espn insider', 'espninsider', 'espn.com', 'espn*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 4.99 },
    billingCycles: ['monthly', 'yearly'],
  },
  {
    name: 'Sports Illustrated',
    displayName: 'Sports Illustrated',
    category: 'News & Media',
    website: 'https://si.com',
    keywords: ['sports illustrated', 'sportsillustrated', 'si.com', 'sports illustrated*'],
    countries: ['US'],
    currency: ['USD'],
    typicalAmounts: { USD: 4.99 },
    billingCycles: ['monthly', 'yearly'],
  },
];

